### ISSUE TITLE
[WCAG20-TECH] XML形式で翻訳を作成する

### ISSUE THREAD

**Issue by momdo** [momdo/momdo.github.io#75]
related #7 
waic/wcag20 にすぐにコミットできるよう、スタイルに合わせて作成する

**Comment by momdo** [comment]
OmegaTにXMLのファイルフィルターは用意されていないため、Okapiのファイルフィルターを設定する必要がある。

**Comment by momdo** [comment]
https://github.com/momdo/wcag20/commit/8c15c267020aa10370c6c0dc3a76f202162908a7 を作成してみた。

**Comment by momdo** [comment]
汎用XML形式については、Okapi RainbowでXLIFFに変換した上で翻訳を進めれば良さそう。

OmegaT補助ツールとしてのOkapi Rainbow - 血統の森+はてな http://d.hatena.ne.jp/momdo/20140406/p1

フィルターについてはHTMLから流用して、暫定的に次のようにすればよいと思われる。
```
assumeWellformed: true
preserve_whitespace: false
  p:
    ruleTypes: [TEXTUNIT]
    idAttributes: [id]
    elementType: paragraph
  att:
    ruleTypes: [INLINE]
  codeblock:
    ruleTypes: [TEXTUNIT, PRESERVE_WHITESPACE]
    idAttributes: [id]
  code:
    ruleTypes: [TEXTUNIT, PRESERVE_WHITESPACE]
  loc:
    ruleTypes: [INLINE]
    elementType: link
    translatableAttributes: [title, accesskey]
    writableLocalizableAttributes: [href]
  specref:
    ruleTypes: [INLINE]
  prop:
    ruleTypes: [INLINE]
```
